entraId:
  entraIDTenantID: 62366534-1ec3-4962-8869-9b5535279d0b
  entraIDClientID: 2d9d2088-1162-4358-9032-00436b737ef5
  entraIDClientSecret: secret

baseUrl: http://localhost:8080
sessionSecret: secret
DevMode: devMode

logging:
  LogFormat: text
  LogLevel: debug

union:
  clientID: 2c7f655b-1b4b-4f29-8c1e-24c011d5a605
  clientSecret: secret
  clientSecretEnvVar: UNION_CLIENT_SECRET
  endpoint: union.dev.data.nav.no
  org: union-nav

k8s:
  fleetHostProjectNumber: 161853196256
  membershipName: dev-union-restricted
  location: europe-west1
