apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: entra-id-client-secret
  namespace: union-api
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: gcp-secret-manager
  target:
    name: entra-id-client-secret
    creationPolicy: Owner
  data:
    - secretKey: client-secret
      remoteRef:
        key: union-api-web-client-secret
