apiVersion: networking.gke.io/v1
kind: HealthCheckPolicy
metadata:
  name: union-api
  namespace: union-api
spec:
  default:
    config:
      type: HTTP
      httpHealthCheck:
        port: 8080
        requestPath: /isalive
  targetRef:
    group: ""
    kind: Service
    name: union-api
